version: 2

models:
  - name: int_sales_details
    description: "Enriched sales details with product info and financials"
    columns:
      - name: order_detail_id
        tests:
          - unique
          - not_null
      - name: sales_order_id
        tests:
          - not_null
          - relationships:
              to: ref('brnz_sales_orders')
              field: sales_order_id
      - name: product_id
        tests:
          - relationships:
              to: ref('brnz_products')
              field: product_id
      - name: gross_amount
        tests: 
          - not_null
      - name: order_status_description
        tests:
          - accepted_values:
              values: ['In Process', 'Approved', 'Backordered', 'Rejected', 'Shipped', 'Cancelled', 'Unknown']

  - name: int_customer_profile
    description: "Customer profiles with segmentation"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('brnz_customers')
              field: customer_id
      - name: customer_type
        tests:
          - accepted_values:
              values: ['Store', 'Individual']
      - name: marketing_segment
        tests:
          - accepted_values:
              values: ['Opt-Out', 'AdventureWorks Only', 'Partners & AdventureWorks', 'Unknown']
