version: 2

models:
  - name: gld_customer_metrics
    description: "Gold: aggregated customer KPIs for analytics & RFM-like usage"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('brnz_customers')
              field: customer_id
      - name: total_orders
        tests:
          - not_null
          - positive_values
      - name: total_revenue
        tests:
          - not_null
          - positive_values
      - name: avg_order_value
      - name: first_order_date
      - name: last_order_date

  - name: gld_product_performance
    description: "Gold: product-level performance metrics"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('brnz_products')
              field: product_id
      - name: total_quantity_sold
        tests:
          - not_null
          - positive_values
      - name: total_revenue
        tests:
          - not_null
          - positive_values
      - name: profit_margin_pct
        tests:
          - pct_between_0_and_100

  - name: gld_sales_summary
    description: "Gold: daily sales summary for dashboards"
    columns:
      - name: order_date
        tests:
          - not_null
          - unique
      - name: total_revenue
        tests:
          - not_null
          - positive_values
      - name: total_orders
        tests:
          - not_null
      - name: year
        description: "Year extracted from order_date"
        tests:
          - not_null
          - positive_values

      - name: month
        description: "Month extracted from order_date (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]

  - name: gld_sales_by_region
    description: "Gold: aggregated sales performance by region/territory"
    columns:
      - name: territory_id
        description: "Region ID mapped from customer territory"
        tests:
          - not_null

      - name: total_orders
        description: "Number of distinct sales orders in this region"
        tests:
          - not_null
          - positive_values

      - name: total_revenue
        description: "Total revenue generated from this region"
        tests:
          - not_null
          - positive_values

      - name: avg_line_value
        description: "Average order line value in this region"
