version: 2

models:
  - name: brnz_customers
    description: |
      Bronze layer customer master data combined with person information.
      
      This table contains cleaned and standardized customer data extracted from the
      AdventureWorks database. It combines customer master records with person 
      information and applies basic data quality rules.
      
      **Data Freshness:** Updated hourly
      **Materialization:** View
      **Row Count:** ~19,000
    
    columns:
      - name: customer_id
        description: "Primary key - Unique customer identifier"
        tests:
          - unique
          - not_null

      - name: person_id
        description: "Foreign key to Person table (may be NULL for store customers)"

      - name: first_name
        description: "Customer first name (cleaned, defaults to UNKNOWN if NULL)"
        tests:
          - not_null

      - name: middle_name
        description: "Customer middle name (may be empty string)"

      - name: last_name
        description: "Customer last name (cleaned, defaults to UNKNOWN if NULL)"
        tests:
          - not_null

      - name: full_name
        description: "Concatenated first and last name"
        tests:
          - not_null

      - name: email_promotion_preference
        description: "Email promotion preference (0=no promo, 1=from AdventureWorks, 2=from partners and AdventureWorks) - defaults to 0 if NULL"
        tests:
          - not_null

      - name: store_id
        description: "Associated store ID (0 if NULL - individual customer)"
        tests:
          - not_null

      - name: territory_id
        description: "Sales territory ID (0 if NULL)"
        tests:
          - not_null

      - name: last_modified_date
        description: "Date when customer record was last updated in source"
        tests:
          - not_null

      - name: dbt_load_timestamp
        description: "Timestamp when record was loaded by DBT"
        tests:
          - not_null

  - name: brnz_sales_orders
    description: |
      Bronze layer sales order data combining headers and line items.
      
      This table contains cleaned and standardized sales order data including header
      information (dates, customer, totals) and line item details (products, quantities).
      Each row represents an order detail line item.
      
      **Data Freshness:** Updated hourly
      **Materialization:** View
      **Row Count:** ~121,000+
    
    tests:
      - line_total_calculation
      - date_range_valid:
          start_date_column: order_date
          end_date_column: ship_date
    
    columns:
      - name: sales_order_id
        description: "Sales order ID - Unique identifier for the sales order"
        tests:
          - not_null

      - name: order_date
        description: "Date the sales order was placed"
        tests:
          - not_null

      - name: due_date
        description: "Date the order is due"

      - name: ship_date
        description: "Date the order was shipped"

      - name: order_status
        description: "Order status (1=Pending, 2=Approved, 3=Backordered, 4=Rejected, 5=Shipped, 6=Cancelled)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]

      - name: is_online_order
        description: "Flag indicating if order was placed online (0=offline, 1=online)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

      - name: order_number
        description: "Human-readable order number (may have duplicates due to order line items)"
        tests:
          - not_null

      - name: purchase_order_number
        description: "Customer purchase order number (NONE if not provided)"

      - name: customer_id
        description: "Primary customer ID for this order"
        tests:
          - not_null
          - relationships:
              to: ref('brnz_customers')
              field: customer_id

      - name: sales_person_id
        description: "Sales person responsible (0 if no sales person)"

      - name: territory_id
        description: "Sales territory ID (0 if NULL)"

      - name: ship_method_id
        description: "Shipping method ID (0 if NULL)"

      - name: order_detail_id
        description: "Primary key for order line item"
        tests:
          - unique
          - not_null

      - name: product_id
        description: "Product ID from this order line"
        tests:
          - not_null
          - relationships:
              to: ref('brnz_products')
              field: product_id

      - name: order_quantity
        description: "Quantity ordered for this line item"
        tests:
          - not_null
          - positive_values

      - name: unit_price
        description: "Unit price at time of order"
        tests:
          - not_null
          - positive_values

      - name: unit_price_discount
        description: "Discount applied to unit price (0-1)"
        tests:
          - not_null

      - name: line_total
        description: "Total for this line item (quantity * unit_price * (1 - discount))"
        tests:
          - not_null
          - positive_values

      - name: order_subtotal
        description: "Order subtotal before tax and freight"
        tests:
          - not_null

      - name: tax_amount
        description: "Tax amount for order"

      - name: freight_amount
        description: "Freight charge for order"

      - name: order_total
        description: "Total order amount (subtotal + tax + freight)"
        tests:
          - not_null

      - name: last_modified_date
        description: "Date when record was last updated in source"
        tests:
          - not_null

      - name: dbt_load_timestamp
        description: "Timestamp when record was loaded by DBT"
        tests:
          - not_null

  - name: brnz_products
    description: |
      Bronze layer product master data combined with category information.
      
      This table contains cleaned and standardized product master data from the
      AdventureWorks Production schema. It includes product attributes, pricing,
      inventory settings, and category classification.
      
      **Data Freshness:** Updated daily
      **Materialization:** View
      **Row Count:** ~504
    
    columns:
      - name: product_id
        description: "Primary key - Unique product identifier"
        tests:
          - unique
          - not_null

      - name: product_name
        description: "Product name/description"
        tests:
          - not_null

      - name: product_number
        description: "Human-readable product number/SKU"
        tests:
          - unique
          - not_null

      - name: is_manufactured
        description: "Flag indicating if product is manufactured in-house (1=yes, 0=no)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

      - name: is_finished_good
        description: "Flag indicating if product is sold (1=yes, 0=no)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

      - name: color
        description: "Product color (UNKNOWN if not specified)"

      - name: safety_stock_level
        description: "Minimum stock level for safety"
        tests:
          - not_null

      - name: reorder_point
        description: "Reorder point quantity"
        tests:
          - not_null

      - name: standard_cost
        description: "Standard manufacturing cost (may be 0 for non-manufactured products)"
        tests:
          - not_null

      - name: list_price
        description: "Official list price (may be 0 for products not for sale)"
        tests:
          - not_null

      - name: size
        description: "Product size (N/A if not applicable)"

      - name: size_unit_measure_code
        description: "Unit of measurement for size (CM, IN, etc.) - N/A if not applicable"

      - name: weight_unit_measure_code
        description: "Unit of measurement for weight (LB, KG, etc.) - N/A if not applicable"

      - name: weight
        description: "Product weight in specified units (0 if NULL)"

      - name: days_to_manufacture
        description: "Days required to manufacture"
        tests:
          - not_null

      - name: product_line
        description: "Product line classification (R=Road, M=Mountain, T=Touring, S=Standard)"

      - name: product_class
        description: "Product class classification (H=High, M=Medium, L=Low)"

      - name: product_style
        description: "Product style classification (U=Unisex, M=Mens, W=Womens)"

      - name: product_subcategory_id
        description: "Foreign key to product subcategory (0 if NULL)"

      - name: product_model_id
        description: "Foreign key to product model (0 if NULL)"

      - name: subcategory_name
        description: "Product subcategory name"

      - name: product_category_id
        description: "Product category ID (0 if NULL)"

      - name: sell_start_date
        description: "Date product became available for sale"
        tests:
          - not_null

      - name: sell_end_date
        description: "Date product stopped being sold (NULL if still active)"

      - name: discontinued_date
        description: "Date product was discontinued (NULL if still active)"

      - name: product_status
        description: "Current product status (ACTIVE or DISCONTINUED)"
        tests:
          - not_null
          - accepted_values:
              values: ['ACTIVE', 'DISCONTINUED']

      - name: last_modified_date
        description: "Date when record was last updated in source"
        tests:
          - not_null

      - name: dbt_load_timestamp
        description: "Timestamp when record was loaded by DBT"
        tests:
          - not_null